/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.Detalle;
import Conexion.Eventos;
import Conexion.Productos;
import Conexion.ProductosDao;
import Conexion.Venta;
import Conexion.VentaDao;
import FiveCodMover.FiveCodMoverJFrame;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Desktop;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author edgar
 */
public class Inventario extends javax.swing.JFrame {

    Productos pro = new Productos();
    ProductosDao proDao = new ProductosDao();
    Venta v = new Venta();
    VentaDao Vdao = new VentaDao();
    Detalle Dv = new Detalle();
    Eventos event = new Eventos();
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel tmp = new DefaultTableModel();
    int item;
    double TotalPagar = 0.00;

    public Inventario() {
        setResizable(false);
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        //proDao.ConsultarProductos(BuscarProducto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void ListarProductos() {
        List<Productos> ListarPro = proDao.ListarProductos();
        modelo = (DefaultTableModel) TablaProductos.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarPro.size(); i++) {
            ob[0] = ListarPro.get(i).getId();
            ob[1] = ListarPro.get(i).getCodigo();
            ob[2] = ListarPro.get(i).getNombre();
            ob[3] = ListarPro.get(i).getCantidad();
            ob[4] = ListarPro.get(i).getPrecio();
            modelo.addRow(ob);
        }
        TablaProductos.setModel(modelo);
    }

    public void ListarVentas() {
        List<Venta> ListarVenta = Vdao.ListarVentas();
        modelo = (DefaultTableModel) TablaHistorial.getModel();
        Object[] ob = new Object[4];
        Date date = new Date();
        for (int i = 0; i < ListarVenta.size(); i++) {
            ob[0] = ListarVenta.get(i).getId();
            ob[1] = ListarVenta.get(i).getCliente();
            ob[2] = ListarVenta.get(i).getTotal();
            ob[3] = new SimpleDateFormat("dd-MM-yyyy").format(date);

            modelo.addRow(ob);
        }
        TablaHistorial.setModel(modelo);
    }
    
    public void LimpiarTabla() {
        int i;
        for (i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        Cerrar = new javax.swing.JLabel();
        Panel = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelPagar = new javax.swing.JPanel();
        CajaID = new javax.swing.JTextField();
        Usuario1 = new javax.swing.JLabel();
        Producto1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Cantidad1 = new javax.swing.JLabel();
        CajaCantidadPagar = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVentas = new javax.swing.JTable();
        Precio2 = new javax.swing.JLabel();
        CajaClientePagar = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Precio4 = new javax.swing.JLabel();
        CajaTotalPagar = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        BotonPagarPagar = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        CajaProdVenta = new javax.swing.JTextField();
        Precio5 = new javax.swing.JLabel();
        CajaPrecioVent = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        CajaStock = new javax.swing.JTextField();
        Precio6 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        BotonEliminar1 = new javax.swing.JButton();
        PanelProductos = new javax.swing.JPanel();
        CajaCodigo = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Producto = new javax.swing.JLabel();
        CajaProducto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Cantidad = new javax.swing.JLabel();
        CajaCantidad = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Precio = new javax.swing.JLabel();
        CajaPrecio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        BotonAgregar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        CajaIdPro = new javax.swing.JTextField();
        PanelVentas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaHistorial = new javax.swing.JTable();
        PanelConfiguracion = new javax.swing.JPanel();
        Usuario2 = new javax.swing.JLabel();
        CajaClaveActual = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        Usuario3 = new javax.swing.JLabel();
        CajaClaveNueva = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        Usuario4 = new javax.swing.JLabel();
        CajaClaveNueva2 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        CambiarClave = new javax.swing.JButton();
        PanelBotones = new javax.swing.JPanel();
        BotonVentas = new javax.swing.JButton();
        BotonPagar = new javax.swing.JButton();
        BotonConfiguracion = new javax.swing.JButton();
        BotonProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setBackground(new java.awt.Color(51, 0, 255));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar (1).png"))); // NOI18N
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        PanelFondo.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        Panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panel.png"))); // NOI18N
        PanelFondo.add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoMouseDragged(evt);
            }
        });
        PanelFondo.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 110));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 110));

        PanelPagar.setBackground(new java.awt.Color(255, 255, 255));
        PanelPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CajaID.setBorder(null);
        CajaID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaIDActionPerformed(evt);
            }
        });
        CajaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaIDKeyTyped(evt);
            }
        });
        PanelPagar.add(CajaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        Usuario1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(51, 51, 168));
        Usuario1.setText("Codigo:");
        PanelPagar.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        Producto1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Producto1.setForeground(new java.awt.Color(51, 51, 168));
        Producto1.setText("Producto:");
        PanelPagar.add(Producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator6.setForeground(new java.awt.Color(102, 102, 102));
        PanelPagar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 20));

        Cantidad1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Cantidad1.setForeground(new java.awt.Color(51, 51, 168));
        Cantidad1.setText("Cantidad:");
        PanelPagar.add(Cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        CajaCantidadPagar.setBorder(null);
        CajaCantidadPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaCantidadPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCantidadPagarActionPerformed(evt);
            }
        });
        CajaCantidadPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaCantidadPagarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaCantidadPagarKeyTyped(evt);
            }
        });
        PanelPagar.add(CajaCantidadPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 60, 20));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator8.setForeground(new java.awt.Color(102, 102, 102));
        PanelPagar.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 60, 20));

        TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane2.setViewportView(TablaVentas);
        if (TablaVentas.getColumnModel().getColumnCount() > 0) {
            TablaVentas.getColumnModel().getColumn(0).setPreferredWidth(20);
            TablaVentas.getColumnModel().getColumn(2).setPreferredWidth(30);
            TablaVentas.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        PanelPagar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 200));

        Precio2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Precio2.setForeground(new java.awt.Color(51, 51, 168));
        Precio2.setText("Cliente:");
        PanelPagar.add(Precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        CajaClientePagar.setBorder(null);
        CajaClientePagar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaClientePagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaClientePagarActionPerformed(evt);
            }
        });
        CajaClientePagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaClientePagarKeyTyped(evt);
            }
        });
        PanelPagar.add(CajaClientePagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 20));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator7.setForeground(new java.awt.Color(102, 102, 102));
        PanelPagar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 20));

        Precio4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Precio4.setForeground(new java.awt.Color(51, 51, 168));
        Precio4.setText("Total a pagar:");
        PanelPagar.add(Precio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        CajaTotalPagar.setEditable(false);
        CajaTotalPagar.setBorder(null);
        CajaTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaTotalPagarActionPerformed(evt);
            }
        });
        PanelPagar.add(CajaTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 110, 20));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator10.setForeground(new java.awt.Color(102, 102, 102));
        PanelPagar.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, 20));

        BotonPagarPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras.png"))); // NOI18N
        BotonPagarPagar.setBorder(null);
        BotonPagarPagar.setBorderPainted(false);
        BotonPagarPagar.setContentAreaFilled(false);
        BotonPagarPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPagarPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagarPagarActionPerformed(evt);
            }
        });
        PanelPagar.add(BotonPagarPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 40));

        jSeparator11.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator11.setForeground(new java.awt.Color(102, 102, 102));
        PanelPagar.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 110, 20));

        CajaProdVenta.setEditable(false);
        CajaProdVenta.setBorder(null);
        CajaProdVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaProdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaProdVentaActionPerformed(evt);
            }
        });
        CajaProdVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaProdVentaKeyPressed(evt);
            }
        });
        PanelPagar.add(CajaProdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 20));

        Precio5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Precio5.setForeground(new java.awt.Color(51, 51, 168));
        Precio5.setText("Precio:");
        PanelPagar.add(Precio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        CajaPrecioVent.setEditable(false);
        CajaPrecioVent.setBorder(null);
        CajaPrecioVent.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaPrecioVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaPrecioVentActionPerformed(evt);
            }
        });
        PanelPagar.add(CajaPrecioVent, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, 20));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator12.setForeground(new java.awt.Color(102, 102, 102));
        PanelPagar.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 110, 20));

        CajaStock.setEditable(false);
        CajaStock.setBorder(null);
        CajaStock.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaStockActionPerformed(evt);
            }
        });
        PanelPagar.add(CajaStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 50, 20));

        Precio6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Precio6.setForeground(new java.awt.Color(51, 51, 168));
        Precio6.setText("Stock:");
        PanelPagar.add(Precio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jSeparator13.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator13.setForeground(new java.awt.Color(102, 102, 102));
        PanelPagar.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 50, 20));

        BotonEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        BotonEliminar1.setBorder(null);
        BotonEliminar1.setBorderPainted(false);
        BotonEliminar1.setContentAreaFilled(false);
        BotonEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminar1ActionPerformed(evt);
            }
        });
        PanelPagar.add(BotonEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, 40));

        jTabbedPane1.addTab("tab1", PanelPagar);

        PanelProductos.setBackground(new java.awt.Color(255, 255, 255));
        PanelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CajaCodigo.setBorder(null);
        CajaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCodigoActionPerformed(evt);
            }
        });
        CajaCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaCodigoKeyTyped(evt);
            }
        });
        PanelProductos.add(CajaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        Usuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(51, 51, 168));
        Usuario.setText("Codigo:");
        PanelProductos.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        PanelProductos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 90, 20));

        Producto.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Producto.setForeground(new java.awt.Color(51, 51, 168));
        Producto.setText("Producto:");
        PanelProductos.add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        CajaProducto.setBorder(null);
        CajaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaProductoActionPerformed(evt);
            }
        });
        CajaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaProductoKeyTyped(evt);
            }
        });
        PanelProductos.add(CajaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 20));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        PanelProductos.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 20));

        Cantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(51, 51, 168));
        Cantidad.setText("Cantidad:");
        PanelProductos.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        CajaCantidad.setBorder(null);
        CajaCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaCantidadActionPerformed(evt);
            }
        });
        CajaCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaCantidadKeyTyped(evt);
            }
        });
        PanelProductos.add(CajaCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 70, 20));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        PanelProductos.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 130, 20));

        Precio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Precio.setForeground(new java.awt.Color(51, 51, 168));
        Precio.setText("Precio:");
        PanelProductos.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        CajaPrecio.setBorder(null);
        CajaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaPrecioActionPerformed(evt);
            }
        });
        CajaPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CajaPrecioKeyTyped(evt);
            }
        });
        PanelProductos.add(CajaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 90, 20));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        PanelProductos.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 70, 20));

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Codigo", "Producto", "Cantidad", "Precio"
            }
        ));
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setPreferredWidth(10);
            TablaProductos.getColumnModel().getColumn(1).setPreferredWidth(20);
            TablaProductos.getColumnModel().getColumn(3).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        PanelProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 200));

        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/controlar.png"))); // NOI18N
        BotonAgregar.setBorder(null);
        BotonAgregar.setBorderPainted(false);
        BotonAgregar.setContentAreaFilled(false);
        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });
        PanelProductos.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 40));

        BotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BotonEditar.setBorder(null);
        BotonEditar.setBorderPainted(false);
        BotonEditar.setContentAreaFilled(false);
        BotonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });
        PanelProductos.add(BotonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 40));

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        BotonEliminar.setBorder(null);
        BotonEliminar.setBorderPainted(false);
        BotonEliminar.setContentAreaFilled(false);
        BotonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        PanelProductos.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, 40));

        BotonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        BotonActualizar.setBorder(null);
        BotonActualizar.setBorderPainted(false);
        BotonActualizar.setContentAreaFilled(false);
        BotonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        PanelProductos.add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 40));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));
        PanelProductos.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 70, 20));

        CajaIdPro.setEditable(false);
        CajaIdPro.setBorder(null);
        CajaIdPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaIdProActionPerformed(evt);
            }
        });
        PanelProductos.add(CajaIdPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 70, 20));

        jTabbedPane1.addTab("tab2", PanelProductos);

        PanelVentas.setBackground(new java.awt.Color(255, 255, 255));

        TablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre cliente", "Total", "Fecha"
            }
        ));
        jScrollPane3.setViewportView(TablaHistorial);
        if (TablaHistorial.getColumnModel().getColumnCount() > 0) {
            TablaHistorial.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        javax.swing.GroupLayout PanelVentasLayout = new javax.swing.GroupLayout(PanelVentas);
        PanelVentas.setLayout(PanelVentasLayout);
        PanelVentasLayout.setHorizontalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PanelVentasLayout.setVerticalGroup(
            PanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", PanelVentas);

        PanelConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        PanelConfiguracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Usuario2.setForeground(new java.awt.Color(51, 51, 168));
        Usuario2.setText("Ingrese contraseña actual:");
        PanelConfiguracion.add(Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 20));

        CajaClaveActual.setBorder(null);
        CajaClaveActual.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaClaveActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaClaveActualActionPerformed(evt);
            }
        });
        CajaClaveActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaClaveActualKeyPressed(evt);
            }
        });
        PanelConfiguracion.add(CajaClaveActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 270, 20));

        jSeparator14.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator14.setForeground(new java.awt.Color(102, 102, 102));
        PanelConfiguracion.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 270, 20));

        Usuario3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Usuario3.setForeground(new java.awt.Color(51, 51, 168));
        Usuario3.setText("Ingrese nueva contraseña :");
        PanelConfiguracion.add(Usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 20));

        CajaClaveNueva.setBorder(null);
        CajaClaveNueva.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaClaveNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaClaveNuevaActionPerformed(evt);
            }
        });
        CajaClaveNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaClaveNuevaKeyPressed(evt);
            }
        });
        PanelConfiguracion.add(CajaClaveNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 270, 20));

        jSeparator15.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator15.setForeground(new java.awt.Color(102, 102, 102));
        PanelConfiguracion.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, 20));

        Usuario4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Usuario4.setForeground(new java.awt.Color(51, 51, 168));
        Usuario4.setText("Ingrese de nuevo la nueva contraseña:");
        PanelConfiguracion.add(Usuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 20));

        CajaClaveNueva2.setBorder(null);
        CajaClaveNueva2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CajaClaveNueva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaClaveNueva2ActionPerformed(evt);
            }
        });
        CajaClaveNueva2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CajaClaveNueva2KeyPressed(evt);
            }
        });
        PanelConfiguracion.add(CajaClaveNueva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 20));

        jSeparator16.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator16.setForeground(new java.awt.Color(102, 102, 102));
        PanelConfiguracion.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 270, 20));

        CambiarClave.setBackground(new java.awt.Color(204, 204, 204));
        CambiarClave.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        CambiarClave.setText("Actualizar contraseña");
        CambiarClave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarClaveActionPerformed(evt);
            }
        });
        PanelConfiguracion.add(CambiarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jTabbedPane1.addTab("tab4", PanelConfiguracion);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 500, 330));

        PanelBotones.setBackground(new java.awt.Color(11, 11, 77));
        PanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonVentas.setBackground(new java.awt.Color(11, 11, 77));
        BotonVentas.setForeground(new java.awt.Color(11, 11, 77));
        BotonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ventas.png"))); // NOI18N
        BotonVentas.setBorder(null);
        BotonVentas.setBorderPainted(false);
        BotonVentas.setContentAreaFilled(false);
        BotonVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVentasActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 50));

        BotonPagar.setBackground(new java.awt.Color(11, 11, 77));
        BotonPagar.setForeground(new java.awt.Color(11, 11, 77));
        BotonPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pagar.png"))); // NOI18N
        BotonPagar.setBorder(null);
        BotonPagar.setBorderPainted(false);
        BotonPagar.setContentAreaFilled(false);
        BotonPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagarActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        BotonConfiguracion.setBackground(new java.awt.Color(11, 11, 77));
        BotonConfiguracion.setForeground(new java.awt.Color(11, 11, 77));
        BotonConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Configuracion.png"))); // NOI18N
        BotonConfiguracion.setBorder(null);
        BotonConfiguracion.setBorderPainted(false);
        BotonConfiguracion.setContentAreaFilled(false);
        BotonConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfiguracionActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 50));

        BotonProductos.setBackground(new java.awt.Color(11, 11, 77));
        BotonProductos.setForeground(new java.awt.Color(11, 11, 77));
        BotonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Productos.png"))); // NOI18N
        BotonProductos.setBorder(null);
        BotonProductos.setBorderPainted(false);
        BotonProductos.setContentAreaFilled(false);
        BotonProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProductosActionPerformed(evt);
            }
        });
        PanelBotones.add(BotonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 50));

        getContentPane().add(PanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);        // TODO add your handling code here:
    }//GEN-LAST:event_FondoMouseDragged

    private void BotonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVentasActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        
        LimpiarTabla();
        ListarVentas();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVentasActionPerformed

    private void BotonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagarActionPerformed
        LimpiarTabla();
        LimpiarPagar();
        ListarProductos();
        jTabbedPane1.setSelectedIndex(0);   // TODO add your handling code here:
    }//GEN-LAST:event_BotonPagarActionPerformed

    private void BotonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfiguracionActionPerformed
        LimpiarTabla();
        ListarProductos();
        jTabbedPane1.setSelectedIndex(3);  // TODO add your handling code here:
    }//GEN-LAST:event_BotonConfiguracionActionPerformed

    private void BotonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProductosActionPerformed
        LimpiarTabla();
        ListarProductos();
        jTabbedPane1.setSelectedIndex(1);// TODO add your handling code here:
    }//GEN-LAST:event_BotonProductosActionPerformed

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseClicked

    private void CajaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCodigoActionPerformed

    private void CajaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaProductoActionPerformed

    private void CajaCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCantidadActionPerformed

    private void CajaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaPrecioActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        if (!"".equals(CajaCodigo.getText()) || !"".equals(CajaProducto.getText()) || !"".equals(CajaCantidad.getText()) || !"".equals(CajaPrecio.getText())) {
            pro.setCodigo(CajaCodigo.getText());
            pro.setNombre(CajaProducto.getText());
            pro.setCantidad(Integer.parseInt(CajaCantidad.getText()));
            pro.setPrecio(Double.parseDouble(CajaPrecio.getText()));
            proDao.RegistrarProductos(pro);
            LimpiarTabla();
            LimpiarProducto();
            ListarProductos();
            JOptionPane.showMessageDialog(null, "Producto registrado con exito");
        } else {
            JOptionPane.showMessageDialog(null, "los campos estan vacios");
        }
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        if (!"".equals(CajaIdPro.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar?");
            if (pregunta == 0) {
                int id = Integer.parseInt(CajaIdPro.getText());
                proDao.EliminarProducto(id);
                LimpiarTabla();
                LimpiarProducto();
                ListarProductos();
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void CajaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaIDActionPerformed

    private void CajaCantidadPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaCantidadPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaCantidadPagarActionPerformed

    private void CajaClientePagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaClientePagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaClientePagarActionPerformed

    private void CajaTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaTotalPagarActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        LimpiarProducto();    // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        int fila = TablaProductos.rowAtPoint(evt.getPoint());
        CajaIdPro.setText(TablaProductos.getValueAt(fila, 0).toString());
        CajaCodigo.setText(TablaProductos.getValueAt(fila, 1).toString());
        CajaProducto.setText(TablaProductos.getValueAt(fila, 2).toString());
        CajaCantidad.setText(TablaProductos.getValueAt(fila, 3).toString());
        CajaPrecio.setText(TablaProductos.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        if ("".equals(CajaIdPro.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(CajaCodigo.getText()) || !"".equals(CajaProducto.getText()) || !"".equals(CajaCantidad.getText()) || !"".equals(CajaPrecio.getText())) {
                pro.setCodigo(CajaCodigo.getText());
                pro.setNombre(CajaProducto.getText());
                pro.setCantidad(Integer.parseInt(CajaCantidad.getText()));
                pro.setPrecio(Double.parseDouble(CajaPrecio.getText()));
                pro.setId(Integer.parseInt(CajaIdPro.getText()));
                proDao.ModificarProducto(pro);
                JOptionPane.showMessageDialog(null, "Producto modificado");
                LimpiarTabla();
                LimpiarProducto();
                ListarProductos();
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void CajaIdProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaIdProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaIdProActionPerformed

    private void CajaIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaIDKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(CajaID.getText())) {
                String Cod = CajaID.getText();
                pro = proDao.BuscarPro(Cod);
                if (pro.getNombre() != null) {
                    CajaProdVenta.setText("" + pro.getNombre());
                    CajaPrecioVent.setText("" + pro.getPrecio());
                    CajaStock.setText("" + pro.getCantidad());
                    CajaCantidadPagar.requestFocus();

                } else {
                    CajaProdVenta.setText("");
                    CajaPrecioVent.setText("");
                    CajaStock.setText("");
                    CajaID.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el codigo del producto");
                CajaID.requestFocus();
            }
        }
    }//GEN-LAST:event_CajaIDKeyPressed

    private void CajaProdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaProdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaProdVentaActionPerformed

    private void CajaProdVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaProdVentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaProdVentaKeyPressed

    private void CajaPrecioVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaPrecioVentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaPrecioVentActionPerformed

    private void CajaCantidadPagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaCantidadPagarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(CajaCantidadPagar.getText())) {
                String Cod = CajaID.getText();
                String descripcion = CajaProdVenta.getText();
                int cantidad = Integer.parseInt(CajaCantidadPagar.getText());
                double precio = Double.parseDouble(CajaPrecioVent.getText());
                double total = cantidad * precio;
                int stock = Integer.parseInt(CajaStock.getText());
                if (stock >= cantidad) {
                    item = item + 1;
                    modelo = (DefaultTableModel) TablaVentas.getModel();
                    for (int i = 0; i < TablaVentas.getRowCount(); i++) {
                        if (TablaVentas.getValueAt(i, 1).equals(CajaProdVenta.getText())) {
                            JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                            return;
                        }
                    }
                    ArrayList lista = new ArrayList();
                    lista.add(item);
                    lista.add(Cod);
                    lista.add(descripcion);
                    lista.add(cantidad);
                    lista.add(precio);
                    lista.add(total);
                    Object[] O = new Object[5];
                    O[0] = lista.get(1);
                    O[1] = lista.get(2);
                    O[2] = lista.get(3);
                    O[3] = lista.get(4);
                    O[4] = lista.get(5);
                    modelo.addRow(O);
                    TablaVentas.setModel(modelo);
                    Totalpagar();
                    LimpiarPagar();
                    CajaID.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Cantidad no disponible");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese Cantidad");
            }
        }
    }//GEN-LAST:event_CajaCantidadPagarKeyPressed

    private void CajaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaStockActionPerformed

    private void CajaClaveActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaClaveActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaClaveActualActionPerformed

    private void CajaClaveActualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaClaveActualKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaClaveActualKeyPressed

    private void CajaClaveNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaClaveNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaClaveNuevaActionPerformed

    private void CajaClaveNuevaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaClaveNuevaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaClaveNuevaKeyPressed

    private void CajaClaveNueva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaClaveNueva2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaClaveNueva2ActionPerformed

    private void CajaClaveNueva2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaClaveNueva2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaClaveNueva2KeyPressed

    private void CambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiarClaveActionPerformed

    private void BotonPagarPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagarPagarActionPerformed
        
        if (!"".equals(CajaClientePagar.getText()) ) {
        RegistrarVenta();
        RegistrarDetalle();
        ActualizarStock();
        pdf();
        LimpiarTablaVenta();
        CajaClientePagar.setText("");
        CajaTotalPagar.setText("");
            
        } else {
            JOptionPane.showMessageDialog(null, "No tiene escrito el cliente.");
        }
    }//GEN-LAST:event_BotonPagarPagarActionPerformed

    private void BotonEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminar1ActionPerformed
        modelo = (DefaultTableModel) TablaVentas.getModel();
        modelo.removeRow(TablaVentas.getSelectedRow());
        Totalpagar();
        CajaID.requestFocus();
        JOptionPane.showMessageDialog(null, "Venta eliminada");
    }//GEN-LAST:event_BotonEliminar1ActionPerformed

    private void CajaIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaIDKeyTyped
        event.SoloNumeros(evt);
    }//GEN-LAST:event_CajaIDKeyTyped

    private void CajaCantidadPagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaCantidadPagarKeyTyped
        // TODO add your handling code here:
        event.SoloNumeros(evt);
    }//GEN-LAST:event_CajaCantidadPagarKeyTyped

    private void CajaClientePagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaClientePagarKeyTyped
        // TODO add your handling code here:
        event.SoloTexto(evt);
    }//GEN-LAST:event_CajaClientePagarKeyTyped

    private void CajaCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaCodigoKeyTyped
        // TODO add your handling code here:
        event.SoloNumeros(evt);
    }//GEN-LAST:event_CajaCodigoKeyTyped

    private void CajaProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaProductoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CajaProductoKeyTyped

    private void CajaCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaCantidadKeyTyped
        // TODO add your handling code here:
         event.SoloNumeros(evt);
    }//GEN-LAST:event_CajaCantidadKeyTyped

    private void CajaPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CajaPrecioKeyTyped
        // TODO add your handling code here:
        event.Solodecimales(evt, CajaPrecio);
    }//GEN-LAST:event_CajaPrecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonConfiguracion;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonEliminar1;
    private javax.swing.JButton BotonPagar;
    private javax.swing.JButton BotonPagarPagar;
    private javax.swing.JButton BotonProductos;
    private javax.swing.JButton BotonVentas;
    private javax.swing.JTextField CajaCantidad;
    private javax.swing.JTextField CajaCantidadPagar;
    private javax.swing.JTextField CajaClaveActual;
    private javax.swing.JTextField CajaClaveNueva;
    private javax.swing.JTextField CajaClaveNueva2;
    private javax.swing.JTextField CajaClientePagar;
    private javax.swing.JTextField CajaCodigo;
    private javax.swing.JTextField CajaID;
    private javax.swing.JTextField CajaIdPro;
    private javax.swing.JTextField CajaPrecio;
    private javax.swing.JTextField CajaPrecioVent;
    private javax.swing.JTextField CajaProdVenta;
    private javax.swing.JTextField CajaProducto;
    private javax.swing.JTextField CajaStock;
    private javax.swing.JTextField CajaTotalPagar;
    private javax.swing.JButton CambiarClave;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Cantidad1;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Panel;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelConfiguracion;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelPagar;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelVentas;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Precio2;
    private javax.swing.JLabel Precio4;
    private javax.swing.JLabel Precio5;
    private javax.swing.JLabel Precio6;
    private javax.swing.JLabel Producto;
    private javax.swing.JLabel Producto1;
    private javax.swing.JTable TablaHistorial;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TablaVentas;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JLabel Usuario3;
    private javax.swing.JLabel Usuario4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
private void LimpiarProducto() {
        CajaIdPro.setText("");
        CajaCodigo.setText("");
        CajaProducto.setText("");
        CajaCantidad.setText("");
        CajaPrecio.setText("");
    }

    private void LimpiarPagar() {

        CajaID.setText("");
        CajaProdVenta.setText("");
        CajaCantidadPagar.setText("");
        CajaStock.setText("");
        CajaPrecioVent.setText("");

    }

    private void Totalpagar() {
        TotalPagar = 0.00;
        int numfila = TablaVentas.getRowCount();
        for (int i = 0; i < numfila; i++) {
            double cal = Double.parseDouble(String.valueOf(TablaVentas.getModel().getValueAt(i, 4)));
            TotalPagar = TotalPagar + cal;
        }
        CajaTotalPagar.setText(String.format("%.2f", TotalPagar));
    }

    private void RegistrarVenta() {
        String cliente = CajaClientePagar.getText();
        double monto = TotalPagar;
        v.setCliente(cliente);
        v.setTotal(monto);
        Vdao.RegistrarVenta(v);
    }

    private void RegistrarDetalle() {
        int id = Vdao.IdVenta();
        for (int i = 0; i < TablaVentas.getRowCount(); i++) {
            String cod = TablaVentas.getValueAt(i, 0).toString();
            int cant = Integer.parseInt(TablaVentas.getValueAt(i, 2).toString());
            double precio = Double.parseDouble(TablaVentas.getValueAt(i, 3).toString());
            Dv.setCod_pro(cod);
            Dv.setCantidad(cant);
            Dv.setPrecio(precio);
            Dv.setId(id);
            Vdao.RegistrarDetalle(Dv);

        }

    }
            private void ActualizarStock(){
            for (int i = 0; i < TablaVentas.getRowCount(); i++) {
                String cod = TablaVentas.getValueAt(i, 0).toString();
                int cant = Integer.parseInt(TablaVentas.getValueAt(i, 2).toString());
                pro = proDao.BuscarPro(cod);
                int StockActual = pro.getCantidad()-cant;
                Vdao.ActualizarStock(StockActual, cod);
            }
        }
            private void LimpiarTablaVenta(){
                modelo = (DefaultTableModel) TablaVentas.getModel();
                int fila = TablaVentas.getRowCount();
                for (int i = 0; i < fila; i++) {
                    modelo.removeRow(0);
                }
            }
    private void pdf(){
        try {
            FileOutputStream archivo;
            File file = new File("src/pdf/venta.pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/imagenes/panel.png");
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN,12,Font.BOLD,BaseColor.BLUE);
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("Fecha: "+ new SimpleDateFormat("dd-MM-yyyy").format(date)+"\n\n");
            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f,30f,70f,40f};
            Encabezado.setWidths(ColumnaEncabezado);
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
            Encabezado.addCell(img);
            
            
            String nom = "Variedades Doña Leidy";
            String tel = "3151234578";
            String dir = "Calle 11 #11-85 barrio San Judas";
            
            Encabezado.addCell("");
            Encabezado.addCell("Nombre: "+nom+"\nTelefono: "+tel+"\nDireccion: "+dir);
            Encabezado.addCell(fecha);
            doc.add(Encabezado);
            
            Paragraph cli = new Paragraph();
            cli.add(Chunk.NEWLINE);
            cli.add("Datos cliente: "+CajaClientePagar.getText()+"\n\n");
            
            
            PdfPTable tablacli = new PdfPTable(1);
            tablacli.setWidthPercentage(100);
            tablacli.getDefaultCell().setBorder(0);
            float[] ColumnaCli = new float[]{30f};
            tablacli.setWidths(ColumnaCli);
            tablacli.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cli1 = new PdfPCell(new Phrase("Dato Cliente:",negrita));
            cli1.setBorder(0);
            tablacli.addCell(cli1);
            tablacli.addCell(CajaClientePagar.getText());
            
            doc.add(tablacli);
            
            
            PdfPTable tablapro = new PdfPTable(4);
            tablapro.setWidthPercentage(100);
            tablapro.getDefaultCell().setBorder(0);
            float[] ColumnaPro = new float[]{20f,30f,70f,40f};
            tablapro.setWidths(ColumnaPro);
            tablapro.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell pro1 = new PdfPCell(new Phrase("Cantidad",negrita));
            PdfPCell pro2 = new PdfPCell(new Phrase("Descripcion",negrita));
            PdfPCell pro3 = new PdfPCell(new Phrase("Precio Unitario",negrita));
            PdfPCell pro4 = new PdfPCell(new Phrase("Total",negrita));
            pro1.setBorder(0);
            pro2.setBorder(0);
            pro3.setBorder(0);
            pro4.setBorder(0);
 
            tablapro.addCell(pro1);
            tablapro.addCell(pro2);
            tablapro.addCell(pro3);
            tablapro.addCell(pro4);
            for (int i = 0; i < TablaVentas.getRowCount(); i++) {
                String producto = TablaVentas.getValueAt(i, 1).toString();
                String cantidad = TablaVentas.getValueAt(i, 2).toString();      
                String precio = TablaVentas.getValueAt(i, 3).toString();
                String total = TablaVentas.getValueAt(i, 4).toString();
                tablapro.addCell(cantidad);
                tablapro.addCell(producto);
                tablapro.addCell(precio);
                tablapro.addCell(total);
            }
            doc.add(tablapro);
            
            Paragraph info = new Paragraph();
            info.add(Chunk.NEWLINE);
            info.add("Total a pagar: "+ TotalPagar);
            info.setAlignment(Element.ALIGN_RIGHT);
            doc.add(info);
            
            Paragraph mensaje = new Paragraph();
            mensaje.add(Chunk.NEWLINE);
            mensaje.add("Gracias por su compra");
            mensaje.setAlignment(Element.ALIGN_CENTER);
            doc.add(mensaje);
            
            doc.close();               
            archivo.close();
            Desktop.getDesktop().open(file);
        } catch (DocumentException | IOException e) {
            System.out.println(e.toString());
        }
    }
}
