/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.LoginDao;
import Conexion.login;
import FiveCodMover.FiveCodMoverJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author edgar
 */
public class Login extends javax.swing.JFrame {

    login lg = new login();
    LoginDao login = new LoginDao();

    public Login() {

        setResizable(false);
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void validar() {

        String usuario = CajaUsuario.getText();
        String pass = String.valueOf(CajaContraseña.getPassword());
        if (!"".equals(usuario) || !"".equals(pass)) {

            lg = login.log(usuario, pass);
            if (lg.getUsuario() != null && lg.getPass() != null) {
                Inventario inv = new Inventario();
                inv.setVisible(true);
                
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecta");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        IconoLogin = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        CajaUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Contraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        CajaContraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        FondoLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(684, 400));
        setMinimumSize(new java.awt.Dimension(684, 400));
        setPreferredSize(new java.awt.Dimension(682, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        PanelLogin.setForeground(new java.awt.Color(255, 255, 255));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contraseña.png"))); // NOI18N
        PanelLogin.add(IconoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        Usuario.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(51, 51, 168));
        Usuario.setText("Usuario:");
        PanelLogin.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 125, -1, -1));

        CajaUsuario.setBorder(null);
        CajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaUsuarioActionPerformed(evt);
            }
        });
        PanelLogin.add(CajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 152, 237, 30));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        PanelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 188, 243, 10));

        Contraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(51, 51, 168));
        Contraseña.setText("Contraseña:");
        PanelLogin.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 204, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        PanelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 274, 243, 11));

        CajaContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CajaContraseña.setBorder(null);
        PanelLogin.add(CajaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 231, 243, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        PanelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 303, -1, 61));

        getContentPane().add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 330, 380));

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar (1).png"))); // NOI18N
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        FondoLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoLoginMouseDragged(evt);
            }
        });
        FondoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoLoginMousePressed(evt);
            }
        });
        getContentPane().add(FondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 270, 400));

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 210, 140));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel3.setText("a buen precio");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jLabel4.setText("Donde encuentras de todo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 310, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaUsuarioActionPerformed

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseClicked

    private void FondoLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoLoginMousePressed
//FiveCodMoverJFrame.MouseDraggedFrame(evt, this);        // TODO add your handling code here:
    }//GEN-LAST:event_FondoLoginMousePressed

    private void FondoLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoLoginMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);        // TODO add your handling code here:
    }//GEN-LAST:event_FondoLoginMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
           validar();     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CajaContraseña;
    private javax.swing.JTextField CajaUsuario;
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JLabel IconoLogin;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
